name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        echo "Iniciando login"
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        echo "Fin de login"
        
    - name: Build docker image
      run: |
        echo "Creando build"
        docker build -t grg0teachorly/docker-graphql:1.0.1 .
        docker build -t grg0teachorly/docker-graphql:latest .
        echo "Build creado"
    
    - name: Push image to DockerHub
      run: |
        echo "Pushing imagen a DH"
        docker push grg0teachorly/docker-graphql:1.0.1
        docker push grg0teachorly/docker-graphql:latest
        echo "Image pushed to DHub Whaleá"

      
#     - name: Build the Docker image
#       run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    
